name: Docker Build ve Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Kodu Çek
    - name: Kodu Getir
      uses: actions/checkout@v3
      
    # 2. Docker Hub'a Giris Yap (Sifreleri Secret'tan aliyor)
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # 3. İmajı Oluştur ve Gönder
    - name: Build ve Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # Etiket: KullaniciAdin/ImajAdin:latest
        tags: ${{ secrets.DOCKER_USERNAME }}/benim-sitem:latest